-- Minimal administration model for the private Pokefuta deployment.

alter table public.users
  add column if not exists is_admin boolean not null default false,
  add column if not exists is_active boolean not null default true,
  add column if not exists must_change_password boolean not null default false;

alter table public.pokefuta
  add column if not exists is_active boolean not null default true;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references public.users(id),
  action text not null,
  target_type text not null,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_logs enable row level security;
revoke all on table public.admin_audit_logs from anon, authenticated;
revoke all on sequence public.admin_audit_logs_id_seq from anon, authenticated;

create index if not exists admin_audit_logs_created_at_idx
  on public.admin_audit_logs (created_at desc);

-- The first administrator. Further administrators are managed from /admin/users.
update public.users
set is_admin = true,
    is_active = true,
    updated_at = now()
where lower(user_id) = 'aka';

