"use client";

import { useMemo, useState } from "react";
import { PokefutaRow } from "../../lib/pokefuta/listData";
import { buildRegionSections, getPrefectureName, REGION_LABELS } from "../../utils/pokefutaGrouping";

export default function PokefutaSelector({ rows, selectedIds, onChange, ownedOnly, selectionLabel, limit, initiallyRevealSelected = false }: { rows: PokefutaRow[]; selectedIds: number[]; onChange: (next: number[]) => void; ownedOnly: boolean; selectionLabel: string; limit: number; initiallyRevealSelected?: boolean }) {
  const selectableRows = useMemo(() => ownedOnly ? rows.filter((row) => row.owned_count > 0) : rows, [ownedOnly, rows]);
  const sections = useMemo(() => buildRegionSections(selectableRows), [selectableRows]);
  const selectedSet = useMemo(() => new Set(selectedIds), [selectedIds]);
  const [expandedRegions, setExpandedRegions] = useState<Set<number>>(() => initiallyRevealSelected ? new Set(rows.filter((row) => selectedSet.has(row.id)).map((row) => row.region_id)) : new Set());
  const [expandedPrefectures, setExpandedPrefectures] = useState<Set<number>>(() => initiallyRevealSelected ? new Set(rows.filter((row) => selectedSet.has(row.id)).map((row) => row.prefecture_id ?? 0)) : new Set());
  const toggleItem = (id: number) => selectedSet.has(id) ? onChange(selectedIds.filter((value) => value !== id)) : selectedIds.length < limit && onChange([...selectedIds, id]);

  if (!selectableRows.length) return <p className="rounded-lg bg-gray-50 px-4 py-6 text-center text-sm text-gray-500">{ownedOnly ? "所持登録されているポケふたがありません。" : "選択できるポケふたがありません。"}</p>;
  return <div className="space-y-3"><div className="sticky top-0 z-10 flex items-center justify-between rounded-lg border bg-white px-4 py-3 shadow-sm"><span className="text-sm font-semibold text-gray-700">選択中</span><span className={`font-bold ${selectedIds.length >= limit ? "text-red-600" : "text-emerald-700"}`}>{selectedIds.length} / {limit}種類</span></div>{sections.map((section) => {
    const regionOpen = expandedRegions.has(section.regionId);
    return <section key={section.regionId} className="overflow-hidden rounded-xl border bg-white"><button type="button" onClick={() => setExpandedRegions((previous) => { const next = new Set(previous); next.has(section.regionId) ? next.delete(section.regionId) : next.add(section.regionId); return next; })} className="flex w-full items-center justify-between px-4 py-3 text-sm font-semibold hover:bg-gray-50"><span>{REGION_LABELS[section.regionId]}</span><span className="text-xs text-gray-500">{regionOpen ? "閉じる" : "開く"}</span></button>{regionOpen && <><div className="flex flex-wrap gap-2 border-t p-3">{section.prefectureIdsToRender.map((prefectureId) => <button key={prefectureId} type="button" onClick={() => setExpandedPrefectures((previous) => { const next = new Set(previous); next.has(prefectureId) ? next.delete(prefectureId) : next.add(prefectureId); return next; })} className={`rounded-full border px-3 py-2 text-sm ${expandedPrefectures.has(prefectureId) ? "border-emerald-600 bg-emerald-600 text-white" : "bg-white"}`}>{getPrefectureName(prefectureId)}</button>)}</div>{section.prefectureIdsToRender.map((prefectureId) => expandedPrefectures.has(prefectureId) && <div key={prefectureId} className="border-t p-3"><h3 className="mb-3 text-sm font-semibold text-gray-600">{getPrefectureName(prefectureId)}</h3><div className="grid grid-cols-3 gap-2 sm:grid-cols-4 md:grid-cols-5">{(section.rowsByPrefectureId.get(prefectureId) ?? []).map((row) => { const selected = selectedSet.has(row.id); const disabled = !selected && selectedIds.length >= limit; return <button key={row.id} type="button" disabled={disabled} aria-pressed={selected} aria-label={`${selectionLabel}：${row.city_name}`} onClick={() => toggleItem(row.id)} className={`relative rounded-xl border p-1.5 text-center shadow-sm ${selected ? "border-emerald-500 bg-lime-200 ring-2 ring-emerald-300" : "bg-white disabled:opacity-35"}`}><img src={row.image_url || "/no-image.png"} loading="lazy" decoding="async" onError={(event) => { event.currentTarget.src = "/no-image.png"; }} alt="" className="aspect-square w-full rounded-full object-cover" />{selected && <span className="absolute right-2 top-2 flex h-6 w-6 items-center justify-center rounded-full bg-emerald-600 text-sm font-bold text-white">✓</span>}<span className="mt-2 block truncate text-xs font-semibold text-gray-700">{row.city_name}</span><span className="block text-[10px] text-gray-500">所持 {row.owned_count}枚</span></button>; })}</div></div>)}</>}</section>;
  })}</div>;
}
